[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd backend && node server.js"
